package com.bookmyticket.controller;
import com.bookmyticket.entity.*; import com.bookmyticket.repository.*; import com.bookmyticket.service.AuthService; import jakarta.servlet.http.HttpSession; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Controller; import org.springframework.ui.Model; import org.springframework.web.bind.annotation.*; import org.springframework.web.servlet.mvc.support.RedirectAttributes;
@Controller @RequiredArgsConstructor @RequestMapping("/admin")
public class AdminController { private final AuthService auth; private final MovieRepository movies; private final TheaterRepository theaters; private final ShowRepository shows; private final SeatRepository seats; private final BookingRepository bookings;
 private boolean logged(HttpSession s){ return s.getAttribute("ADMIN_ID")!=null; }
 @GetMapping("/login") public String login(){ return "admin/login"; }
 @PostMapping("/login") public String doLogin(@RequestParam String username,@RequestParam String password,HttpSession session,RedirectAttributes ra){ return auth.loginAdmin(username,password).map(a->{session.setAttribute("ADMIN_ID",a.getId()); session.setAttribute("ADMIN_NAME",a.getName()); return "redirect:/admin/dashboard";}).orElseGet(()->{ra.addFlashAttribute("error","Invalid admin username or password"); return "redirect:/admin/login";}); }
 @GetMapping("/logout") public String logout(HttpSession s){ s.invalidate(); return "redirect:/admin/login"; }
 @GetMapping({"","/dashboard"}) public String dashboard(Model m,HttpSession s){ if(!logged(s)) return "redirect:/admin/login"; m.addAttribute("movieCount",movies.count()); m.addAttribute("theaterCount",theaters.count()); m.addAttribute("showCount",shows.count()); m.addAttribute("bookingCount",bookings.count()); return "admin/dashboard"; }
 @GetMapping("/movies") public String listMovies(Model m,HttpSession s){ if(!logged(s)) return "redirect:/admin/login"; m.addAttribute("movies",movies.findAll()); return "admin/movies"; }
 @GetMapping("/movies/new") public String newMovie(Model m,HttpSession s){ if(!logged(s)) return "redirect:/admin/login"; m.addAttribute("movie",new Movie()); return "admin/movie-form"; }
 @PostMapping("/movies/save") public String saveMovie(@ModelAttribute Movie movie,HttpSession s,RedirectAttributes ra){ if(!logged(s)) return "redirect:/admin/login"; if(movie.getStatus()==null) movie.setStatus(MovieStatus.ACTIVE); movies.save(movie); ra.addFlashAttribute("success","Movie saved successfully"); return "redirect:/admin/movies"; }
 @GetMapping("/movies/edit/{id}") public String editMovie(@PathVariable Long id,Model m,HttpSession s){ if(!logged(s)) return "redirect:/admin/login"; m.addAttribute("movie",movies.findById(id).orElseThrow()); return "admin/movie-form"; }
 @GetMapping("/movies/delete/{id}") public String deleteMovie(@PathVariable Long id,HttpSession s,RedirectAttributes ra){ if(!logged(s)) return "redirect:/admin/login"; movies.deleteById(id); ra.addFlashAttribute("success","Movie deleted"); return "redirect:/admin/movies"; }
 @GetMapping("/theaters") public String theaterPage(Model m,HttpSession s){ if(!logged(s)) return "redirect:/admin/login"; m.addAttribute("theaters",theaters.findAll()); m.addAttribute("theater",new Theater()); return "admin/theaters"; }
 @PostMapping("/theaters/save") public String saveTheater(@ModelAttribute Theater theater,HttpSession s,RedirectAttributes ra){ if(!logged(s)) return "redirect:/admin/login"; theaters.save(theater); ra.addFlashAttribute("success","Theater saved"); return "redirect:/admin/theaters"; }
 @GetMapping("/shows") public String showPage(Model m,HttpSession s){ if(!logged(s)) return "redirect:/admin/login"; m.addAttribute("shows",shows.findAll()); m.addAttribute("show",new Show()); m.addAttribute("movies",movies.findAll()); m.addAttribute("theaters",theaters.findAll()); return "admin/shows"; }
 @PostMapping("/shows/save") public String saveShow(@RequestParam Long movieId,@RequestParam Long theaterId,@ModelAttribute Show show,HttpSession s,RedirectAttributes ra){ if(!logged(s)) return "redirect:/admin/login"; show.setMovie(movies.findById(movieId).orElseThrow()); show.setTheater(theaters.findById(theaterId).orElseThrow()); shows.save(show); ra.addFlashAttribute("success","Show timing added"); return "redirect:/admin/shows"; }
 @GetMapping("/seats") public String seatsPage(@RequestParam(required=false) Long theaterId,Model m,HttpSession s){ if(!logged(s)) return "redirect:/admin/login"; m.addAttribute("theaters",theaters.findAll()); m.addAttribute("selectedTheaterId",theaterId); if(theaterId!=null) m.addAttribute("seats",seats.findByTheaterIdOrderBySeatNumberAsc(theaterId)); return "admin/seats"; }
 @PostMapping("/seats/generate") public String generateSeats(@RequestParam Long theaterId,@RequestParam(defaultValue="6") int rows,@RequestParam(defaultValue="10") int cols,HttpSession s,RedirectAttributes ra){ if(!logged(s)) return "redirect:/admin/login"; Theater t=theaters.findById(theaterId).orElseThrow(); for(char r='A'; r<'A'+rows; r++) for(int c=1;c<=cols;c++){ String no=""+r+c; if(!seats.existsByTheaterIdAndSeatNumber(theaterId,no)) seats.save(Seat.builder().theater(t).seatNumber(no).status(SeatStatus.AVAILABLE).build()); } ra.addFlashAttribute("success","Seats generated"); return "redirect:/admin/seats?theaterId="+theaterId; }
 @GetMapping("/bookings") public String allBookings(Model m,HttpSession s){ if(!logged(s)) return "redirect:/admin/login"; m.addAttribute("bookings",bookings.findAllByOrderByBookingDateTimeDesc()); return "admin/bookings"; }
}
