package com.bookmyticket.controller;
import com.bookmyticket.entity.*; import com.bookmyticket.repository.*; import com.bookmyticket.service.*; import jakarta.servlet.http.HttpSession; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Controller; import org.springframework.ui.Model; import org.springframework.web.bind.annotation.*; import org.springframework.web.servlet.mvc.support.RedirectAttributes; import java.util.*;
@Controller @RequiredArgsConstructor @RequestMapping("/user")
public class UserController { private final AuthService auth; private final MovieRepository movies; private final ShowRepository shows; private final SeatRepository seats; private final BookingRepository bookings; private final BookingService bookingService;
 @GetMapping("/login") public String login(){ return "user/login"; }
 @PostMapping("/login") public String doLogin(@RequestParam String mobile,@RequestParam String password,HttpSession session,RedirectAttributes ra){ return auth.loginUser(mobile,password).map(u->{session.setAttribute("USER_ID",u.getId()); session.setAttribute("USER_MOBILE",u.getMobile()); return "redirect:/user/movies";}).orElseGet(()->{ra.addFlashAttribute("error","Invalid mobile number or password"); return "redirect:/user/login";}); }
 @GetMapping("/logout") public String logout(HttpSession s){ s.invalidate(); return "redirect:/user/login"; }
 private boolean logged(HttpSession s){ return s.getAttribute("USER_ID")!=null; }
 @GetMapping("/movies") public String movieList(Model m,HttpSession s){ if(!logged(s)) return "redirect:/user/login"; m.addAttribute("movies",movies.findByStatus(MovieStatus.ACTIVE)); return "user/movies"; }
 @GetMapping("/movie/{id}/shows") public String movieShows(@PathVariable Long id,Model m,HttpSession s){ if(!logged(s)) return "redirect:/user/login"; m.addAttribute("movie",movies.findById(id).orElseThrow()); m.addAttribute("shows",shows.findByMovieId(id)); return "user/shows"; }
 @GetMapping("/show/{id}/seats") public String seatPage(@PathVariable Long id,Model m,HttpSession s){ if(!logged(s)) return "redirect:/user/login"; Show show=shows.findById(id).orElseThrow(); m.addAttribute("show",show); m.addAttribute("seats",seats.findByTheaterIdOrderBySeatNumberAsc(show.getTheater().getId())); m.addAttribute("booked",bookingService.bookedSeats(id)); return "user/seats"; }
 @PostMapping("/book") public String book(@RequestParam Long showId,@RequestParam(required=false) List<String> selectedSeats,HttpSession s,RedirectAttributes ra){ if(!logged(s)) return "redirect:/user/login"; try{ Booking b=bookingService.book((Long)s.getAttribute("USER_ID"),showId,selectedSeats); return "redirect:/user/booking/"+b.getId(); }catch(Exception e){ ra.addFlashAttribute("error",e.getMessage()); return "redirect:/user/show/"+showId+"/seats"; } }
 @GetMapping("/booking/{id}") public String confirmation(@PathVariable Long id,Model m,HttpSession s){ if(!logged(s)) return "redirect:/user/login"; m.addAttribute("booking",bookings.findById(id).orElseThrow()); return "user/confirmation"; }
 @GetMapping("/history") public String history(Model m,HttpSession s){ if(!logged(s)) return "redirect:/user/login"; m.addAttribute("bookings",bookings.findByUserIdOrderByBookingDateTimeDesc((Long)s.getAttribute("USER_ID"))); return "user/history"; }
}
